version: "3.9"

services:
  api:
    build: ./server
    container_name: signspeak_api
    ports:
      - "5050:5050"          # host:container - Flask API on port 5050
    restart: unless-stopped

  ui:
    build: ./UI_expo
    container_name: signspeak_ui
    ports:
      - "19006:19006"        # Expo web DevTools / Webpack server
      - "8081:8081"          # Metro JS bundle server
    depends_on:
      - api

